# this is the name of the workflow
name: My first workflow
on:
  # any push will trigger this workflow
- push

jobs:
   my_first_ci:
      # from this point onwards its Ubuntu
      runs-on: ubuntu-latest

      steps:
      - name: get date in Github
        id: get_date_in_github
        run: echo "date in github $(date)"

      - name: list directory
        id: list_directory 
        run: echo "$(ls -l)"

      - name: fail the job
        id: fail_the_job
        run: exit 0

      - name: echo github context
        id: echo_github_context
        run: echo "ref_name ${{ github.ref_name }}\n repository ${{ github.repository}}\n owner ${{ github.repository_owner }}"

      - name: send email 
        id: send_email
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: ${{ secrets.EMAIL_SERVER }}
         server_port: ${{ secrets.EMAIL_PORT }}
         username: ${{ secrets.EMAIL_USER }}
         password: ${{ secrets.EMAIL_PASSWORD }}
         to: 79e8feef-e8a2-4a82-a407-a2f9a40c245e@mailslurp.mx
         from: iYanChenyi@gmail.com
         subject: "Github workflow from ${{ github.ref_name }}"
         body: "The job is ${{ job.status }}"